# Generated by Django 5.2.5 on 2025-08-29 09:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número do Pedido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("BRL", "Brazilian Real"),
                        ],
                        default="BRL",
                        max_length=3,
                        verbose_name="Moeda",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(verbose_name="Endereço de Entrega"),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="Cidade"),
                ),
                (
                    "shipping_state",
                    models.CharField(max_length=100, verbose_name="Estado"),
                ),
                (
                    "shipping_zip_code",
                    models.CharField(max_length=20, verbose_name="CEP"),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        default="Brasil", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="paypal",
                        max_length=50,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID do Pagamento",
                    ),
                ),
                (
                    "paypal_order_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID do Pedido PayPal",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Total"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Nome do Produto"),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, verbose_name="Descrição do Produto"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="pedidos_ord_user_id_e45b91_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="pedidos_ord_status_f3c5b1_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status"], name="pedidos_ord_payment_c14fbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="pedidos_ord_created_f067cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="pedidos_ord_order_n_da423e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="pedidos_ord_order_i_618033_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="pedidos_ord_product_5ab166_idx"
            ),
        ),
    ]
