# Generated by Django 5.2.5 on 2025-08-29 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=100, unique=True, verbose_name="Token"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("used", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperação de Senha",
                "verbose_name_plural": "Tokens de Recuperação de Senha",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="Estado"),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=20, verbose_name="CEP"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Brasil", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("BRL", "Brazilian Real"),
                        ],
                        default="BRL",
                        max_length=3,
                        verbose_name="Moeda Preferida",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificações por Email"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, verbose_name="Emails de Marketing"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Usuário",
                "verbose_name_plural": "Perfis dos Usuários",
            },
        ),
    ]
